name: warp
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

dependencies:
  ffi: ^2.0.1
  json_annotation: ^4.1.0
  flat_buffers: ^2.0.0
  cbor: ^6.3.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  ffigen: ^9.0.0
  build_runner: ^2.1.2
  json_serializable: ^6.1.5

ffigen:
  output: 'lib/warp_generated.dart'
  headers:
    entry-points:
      - '../zcash-warp/binding.h'
# On MacOS
  llvm-path:
    - '/opt/homebrew/Cellar/llvm/16.0.6'
