// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable

library fb;

import 'dart:typed_data' show Uint8List;
import 'package:flat_buffers/flat_buffers.dart' as fb;


class Backup {
  Backup._(this._bc, this._bcOffset);
  factory Backup(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Backup> reader = _BackupReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get name => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  String? get seed => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);
  int get index => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 8, 0);
  String? get sk => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 10);
  String? get fvk => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 12);
  String? get uvk => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 14);
  String? get tsk => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 16);
  int get birth => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 18, 0);
  bool get saved => const fb.BoolReader().vTableGet(_bc, _bcOffset, 20, false);

  @override
  String toString() {
    return 'Backup{name: ${name}, seed: ${seed}, index: ${index}, sk: ${sk}, fvk: ${fvk}, uvk: ${uvk}, tsk: ${tsk}, birth: ${birth}, saved: ${saved}}';
  }

  BackupT unpack() => BackupT(
      name: name,
      seed: seed,
      index: index,
      sk: sk,
      fvk: fvk,
      uvk: uvk,
      tsk: tsk,
      birth: birth,
      saved: saved);

  static int pack(fb.Builder fbBuilder, BackupT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class BackupT implements fb.Packable {
  String? name;
  String? seed;
  int index;
  String? sk;
  String? fvk;
  String? uvk;
  String? tsk;
  int birth;
  bool saved;

  BackupT({
      this.name,
      this.seed,
      this.index = 0,
      this.sk,
      this.fvk,
      this.uvk,
      this.tsk,
      this.birth = 0,
      this.saved = false});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? nameOffset = name == null ? null
        : fbBuilder.writeString(name!);
    final int? seedOffset = seed == null ? null
        : fbBuilder.writeString(seed!);
    final int? skOffset = sk == null ? null
        : fbBuilder.writeString(sk!);
    final int? fvkOffset = fvk == null ? null
        : fbBuilder.writeString(fvk!);
    final int? uvkOffset = uvk == null ? null
        : fbBuilder.writeString(uvk!);
    final int? tskOffset = tsk == null ? null
        : fbBuilder.writeString(tsk!);
    fbBuilder.startTable(9);
    fbBuilder.addOffset(0, nameOffset);
    fbBuilder.addOffset(1, seedOffset);
    fbBuilder.addUint32(2, index);
    fbBuilder.addOffset(3, skOffset);
    fbBuilder.addOffset(4, fvkOffset);
    fbBuilder.addOffset(5, uvkOffset);
    fbBuilder.addOffset(6, tskOffset);
    fbBuilder.addUint32(7, birth);
    fbBuilder.addBool(8, saved);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'BackupT{name: ${name}, seed: ${seed}, index: ${index}, sk: ${sk}, fvk: ${fvk}, uvk: ${uvk}, tsk: ${tsk}, birth: ${birth}, saved: ${saved}}';
  }
}

class _BackupReader extends fb.TableReader<Backup> {
  const _BackupReader();

  @override
  Backup createObject(fb.BufferContext bc, int offset) => 
    Backup._(bc, offset);
}

class BackupBuilder {
  BackupBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(9);
  }

  int addNameOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addSeedOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addIndex(int? index) {
    fbBuilder.addUint32(2, index);
    return fbBuilder.offset;
  }
  int addSkOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }
  int addFvkOffset(int? offset) {
    fbBuilder.addOffset(4, offset);
    return fbBuilder.offset;
  }
  int addUvkOffset(int? offset) {
    fbBuilder.addOffset(5, offset);
    return fbBuilder.offset;
  }
  int addTskOffset(int? offset) {
    fbBuilder.addOffset(6, offset);
    return fbBuilder.offset;
  }
  int addBirth(int? birth) {
    fbBuilder.addUint32(7, birth);
    return fbBuilder.offset;
  }
  int addSaved(bool? saved) {
    fbBuilder.addBool(8, saved);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class BackupObjectBuilder extends fb.ObjectBuilder {
  final String? _name;
  final String? _seed;
  final int? _index;
  final String? _sk;
  final String? _fvk;
  final String? _uvk;
  final String? _tsk;
  final int? _birth;
  final bool? _saved;

  BackupObjectBuilder({
    String? name,
    String? seed,
    int? index,
    String? sk,
    String? fvk,
    String? uvk,
    String? tsk,
    int? birth,
    bool? saved,
  })
      : _name = name,
        _seed = seed,
        _index = index,
        _sk = sk,
        _fvk = fvk,
        _uvk = uvk,
        _tsk = tsk,
        _birth = birth,
        _saved = saved;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? nameOffset = _name == null ? null
        : fbBuilder.writeString(_name!);
    final int? seedOffset = _seed == null ? null
        : fbBuilder.writeString(_seed!);
    final int? skOffset = _sk == null ? null
        : fbBuilder.writeString(_sk!);
    final int? fvkOffset = _fvk == null ? null
        : fbBuilder.writeString(_fvk!);
    final int? uvkOffset = _uvk == null ? null
        : fbBuilder.writeString(_uvk!);
    final int? tskOffset = _tsk == null ? null
        : fbBuilder.writeString(_tsk!);
    fbBuilder.startTable(9);
    fbBuilder.addOffset(0, nameOffset);
    fbBuilder.addOffset(1, seedOffset);
    fbBuilder.addUint32(2, _index);
    fbBuilder.addOffset(3, skOffset);
    fbBuilder.addOffset(4, fvkOffset);
    fbBuilder.addOffset(5, uvkOffset);
    fbBuilder.addOffset(6, tskOffset);
    fbBuilder.addUint32(7, _birth);
    fbBuilder.addBool(8, _saved);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class TransactionInfo {
  TransactionInfo._(this._bc, this._bcOffset);
  factory TransactionInfo(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<TransactionInfo> reader = _TransactionInfoReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get id => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 4, 0);
  String? get txid => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);
  int get height => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 8, 0);
  int get confirmations => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 10, 0);
  int get timestamp => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 12, 0);
  int get amount => const fb.Int64Reader().vTableGet(_bc, _bcOffset, 14, 0);
  String? get address => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 16);
  String? get contact => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 18);
  String? get memo => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 20);

  @override
  String toString() {
    return 'TransactionInfo{id: ${id}, txid: ${txid}, height: ${height}, confirmations: ${confirmations}, timestamp: ${timestamp}, amount: ${amount}, address: ${address}, contact: ${contact}, memo: ${memo}}';
  }

  TransactionInfoT unpack() => TransactionInfoT(
      id: id,
      txid: txid,
      height: height,
      confirmations: confirmations,
      timestamp: timestamp,
      amount: amount,
      address: address,
      contact: contact,
      memo: memo);

  static int pack(fb.Builder fbBuilder, TransactionInfoT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class TransactionInfoT implements fb.Packable {
  int id;
  String? txid;
  int height;
  int confirmations;
  int timestamp;
  int amount;
  String? address;
  String? contact;
  String? memo;

  TransactionInfoT({
      this.id = 0,
      this.txid,
      this.height = 0,
      this.confirmations = 0,
      this.timestamp = 0,
      this.amount = 0,
      this.address,
      this.contact,
      this.memo});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? txidOffset = txid == null ? null
        : fbBuilder.writeString(txid!);
    final int? addressOffset = address == null ? null
        : fbBuilder.writeString(address!);
    final int? contactOffset = contact == null ? null
        : fbBuilder.writeString(contact!);
    final int? memoOffset = memo == null ? null
        : fbBuilder.writeString(memo!);
    fbBuilder.startTable(9);
    fbBuilder.addUint32(0, id);
    fbBuilder.addOffset(1, txidOffset);
    fbBuilder.addUint32(2, height);
    fbBuilder.addUint32(3, confirmations);
    fbBuilder.addUint32(4, timestamp);
    fbBuilder.addInt64(5, amount);
    fbBuilder.addOffset(6, addressOffset);
    fbBuilder.addOffset(7, contactOffset);
    fbBuilder.addOffset(8, memoOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'TransactionInfoT{id: ${id}, txid: ${txid}, height: ${height}, confirmations: ${confirmations}, timestamp: ${timestamp}, amount: ${amount}, address: ${address}, contact: ${contact}, memo: ${memo}}';
  }
}

class _TransactionInfoReader extends fb.TableReader<TransactionInfo> {
  const _TransactionInfoReader();

  @override
  TransactionInfo createObject(fb.BufferContext bc, int offset) => 
    TransactionInfo._(bc, offset);
}

class TransactionInfoBuilder {
  TransactionInfoBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(9);
  }

  int addId(int? id) {
    fbBuilder.addUint32(0, id);
    return fbBuilder.offset;
  }
  int addTxidOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addHeight(int? height) {
    fbBuilder.addUint32(2, height);
    return fbBuilder.offset;
  }
  int addConfirmations(int? confirmations) {
    fbBuilder.addUint32(3, confirmations);
    return fbBuilder.offset;
  }
  int addTimestamp(int? timestamp) {
    fbBuilder.addUint32(4, timestamp);
    return fbBuilder.offset;
  }
  int addAmount(int? amount) {
    fbBuilder.addInt64(5, amount);
    return fbBuilder.offset;
  }
  int addAddressOffset(int? offset) {
    fbBuilder.addOffset(6, offset);
    return fbBuilder.offset;
  }
  int addContactOffset(int? offset) {
    fbBuilder.addOffset(7, offset);
    return fbBuilder.offset;
  }
  int addMemoOffset(int? offset) {
    fbBuilder.addOffset(8, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class TransactionInfoObjectBuilder extends fb.ObjectBuilder {
  final int? _id;
  final String? _txid;
  final int? _height;
  final int? _confirmations;
  final int? _timestamp;
  final int? _amount;
  final String? _address;
  final String? _contact;
  final String? _memo;

  TransactionInfoObjectBuilder({
    int? id,
    String? txid,
    int? height,
    int? confirmations,
    int? timestamp,
    int? amount,
    String? address,
    String? contact,
    String? memo,
  })
      : _id = id,
        _txid = txid,
        _height = height,
        _confirmations = confirmations,
        _timestamp = timestamp,
        _amount = amount,
        _address = address,
        _contact = contact,
        _memo = memo;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? txidOffset = _txid == null ? null
        : fbBuilder.writeString(_txid!);
    final int? addressOffset = _address == null ? null
        : fbBuilder.writeString(_address!);
    final int? contactOffset = _contact == null ? null
        : fbBuilder.writeString(_contact!);
    final int? memoOffset = _memo == null ? null
        : fbBuilder.writeString(_memo!);
    fbBuilder.startTable(9);
    fbBuilder.addUint32(0, _id);
    fbBuilder.addOffset(1, txidOffset);
    fbBuilder.addUint32(2, _height);
    fbBuilder.addUint32(3, _confirmations);
    fbBuilder.addUint32(4, _timestamp);
    fbBuilder.addInt64(5, _amount);
    fbBuilder.addOffset(6, addressOffset);
    fbBuilder.addOffset(7, contactOffset);
    fbBuilder.addOffset(8, memoOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class TransactionInfoExtended {
  TransactionInfoExtended._(this._bc, this._bcOffset);
  factory TransactionInfoExtended(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<TransactionInfoExtended> reader = _TransactionInfoExtendedReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get height => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 4, 0);
  int get timestamp => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 6, 0);
  List<int>? get txid => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 8);
  List<InputTransparent>? get tins => const fb.ListReader<InputTransparent>(InputTransparent.reader).vTableGetNullable(_bc, _bcOffset, 10);
  List<OutputTransparent>? get touts => const fb.ListReader<OutputTransparent>(OutputTransparent.reader).vTableGetNullable(_bc, _bcOffset, 12);
  List<InputShielded>? get sins => const fb.ListReader<InputShielded>(InputShielded.reader).vTableGetNullable(_bc, _bcOffset, 14);
  List<OutputShielded>? get souts => const fb.ListReader<OutputShielded>(OutputShielded.reader).vTableGetNullable(_bc, _bcOffset, 16);
  List<InputShielded>? get oins => const fb.ListReader<InputShielded>(InputShielded.reader).vTableGetNullable(_bc, _bcOffset, 18);
  List<OutputShielded>? get oouts => const fb.ListReader<OutputShielded>(OutputShielded.reader).vTableGetNullable(_bc, _bcOffset, 20);

  @override
  String toString() {
    return 'TransactionInfoExtended{height: ${height}, timestamp: ${timestamp}, txid: ${txid}, tins: ${tins}, touts: ${touts}, sins: ${sins}, souts: ${souts}, oins: ${oins}, oouts: ${oouts}}';
  }

  TransactionInfoExtendedT unpack() => TransactionInfoExtendedT(
      height: height,
      timestamp: timestamp,
      txid: const fb.Uint8ListReader(lazy: false).vTableGetNullable(_bc, _bcOffset, 8),
      tins: tins?.map((e) => e.unpack()).toList(),
      touts: touts?.map((e) => e.unpack()).toList(),
      sins: sins?.map((e) => e.unpack()).toList(),
      souts: souts?.map((e) => e.unpack()).toList(),
      oins: oins?.map((e) => e.unpack()).toList(),
      oouts: oouts?.map((e) => e.unpack()).toList());

  static int pack(fb.Builder fbBuilder, TransactionInfoExtendedT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class TransactionInfoExtendedT implements fb.Packable {
  int height;
  int timestamp;
  List<int>? txid;
  List<InputTransparentT>? tins;
  List<OutputTransparentT>? touts;
  List<InputShieldedT>? sins;
  List<OutputShieldedT>? souts;
  List<InputShieldedT>? oins;
  List<OutputShieldedT>? oouts;

  TransactionInfoExtendedT({
      this.height = 0,
      this.timestamp = 0,
      this.txid,
      this.tins,
      this.touts,
      this.sins,
      this.souts,
      this.oins,
      this.oouts});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? txidOffset = txid == null ? null
        : fbBuilder.writeListUint8(txid!);
    final int? tinsOffset = tins == null ? null
        : fbBuilder.writeList(tins!.map((b) => b.pack(fbBuilder)).toList());
    final int? toutsOffset = touts == null ? null
        : fbBuilder.writeList(touts!.map((b) => b.pack(fbBuilder)).toList());
    final int? sinsOffset = sins == null ? null
        : fbBuilder.writeList(sins!.map((b) => b.pack(fbBuilder)).toList());
    final int? soutsOffset = souts == null ? null
        : fbBuilder.writeList(souts!.map((b) => b.pack(fbBuilder)).toList());
    final int? oinsOffset = oins == null ? null
        : fbBuilder.writeList(oins!.map((b) => b.pack(fbBuilder)).toList());
    final int? ooutsOffset = oouts == null ? null
        : fbBuilder.writeList(oouts!.map((b) => b.pack(fbBuilder)).toList());
    fbBuilder.startTable(9);
    fbBuilder.addUint32(0, height);
    fbBuilder.addUint32(1, timestamp);
    fbBuilder.addOffset(2, txidOffset);
    fbBuilder.addOffset(3, tinsOffset);
    fbBuilder.addOffset(4, toutsOffset);
    fbBuilder.addOffset(5, sinsOffset);
    fbBuilder.addOffset(6, soutsOffset);
    fbBuilder.addOffset(7, oinsOffset);
    fbBuilder.addOffset(8, ooutsOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'TransactionInfoExtendedT{height: ${height}, timestamp: ${timestamp}, txid: ${txid}, tins: ${tins}, touts: ${touts}, sins: ${sins}, souts: ${souts}, oins: ${oins}, oouts: ${oouts}}';
  }
}

class _TransactionInfoExtendedReader extends fb.TableReader<TransactionInfoExtended> {
  const _TransactionInfoExtendedReader();

  @override
  TransactionInfoExtended createObject(fb.BufferContext bc, int offset) => 
    TransactionInfoExtended._(bc, offset);
}

class TransactionInfoExtendedBuilder {
  TransactionInfoExtendedBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(9);
  }

  int addHeight(int? height) {
    fbBuilder.addUint32(0, height);
    return fbBuilder.offset;
  }
  int addTimestamp(int? timestamp) {
    fbBuilder.addUint32(1, timestamp);
    return fbBuilder.offset;
  }
  int addTxidOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addTinsOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }
  int addToutsOffset(int? offset) {
    fbBuilder.addOffset(4, offset);
    return fbBuilder.offset;
  }
  int addSinsOffset(int? offset) {
    fbBuilder.addOffset(5, offset);
    return fbBuilder.offset;
  }
  int addSoutsOffset(int? offset) {
    fbBuilder.addOffset(6, offset);
    return fbBuilder.offset;
  }
  int addOinsOffset(int? offset) {
    fbBuilder.addOffset(7, offset);
    return fbBuilder.offset;
  }
  int addOoutsOffset(int? offset) {
    fbBuilder.addOffset(8, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class TransactionInfoExtendedObjectBuilder extends fb.ObjectBuilder {
  final int? _height;
  final int? _timestamp;
  final List<int>? _txid;
  final List<InputTransparentObjectBuilder>? _tins;
  final List<OutputTransparentObjectBuilder>? _touts;
  final List<InputShieldedObjectBuilder>? _sins;
  final List<OutputShieldedObjectBuilder>? _souts;
  final List<InputShieldedObjectBuilder>? _oins;
  final List<OutputShieldedObjectBuilder>? _oouts;

  TransactionInfoExtendedObjectBuilder({
    int? height,
    int? timestamp,
    List<int>? txid,
    List<InputTransparentObjectBuilder>? tins,
    List<OutputTransparentObjectBuilder>? touts,
    List<InputShieldedObjectBuilder>? sins,
    List<OutputShieldedObjectBuilder>? souts,
    List<InputShieldedObjectBuilder>? oins,
    List<OutputShieldedObjectBuilder>? oouts,
  })
      : _height = height,
        _timestamp = timestamp,
        _txid = txid,
        _tins = tins,
        _touts = touts,
        _sins = sins,
        _souts = souts,
        _oins = oins,
        _oouts = oouts;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? txidOffset = _txid == null ? null
        : fbBuilder.writeListUint8(_txid!);
    final int? tinsOffset = _tins == null ? null
        : fbBuilder.writeList(_tins!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? toutsOffset = _touts == null ? null
        : fbBuilder.writeList(_touts!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? sinsOffset = _sins == null ? null
        : fbBuilder.writeList(_sins!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? soutsOffset = _souts == null ? null
        : fbBuilder.writeList(_souts!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? oinsOffset = _oins == null ? null
        : fbBuilder.writeList(_oins!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? ooutsOffset = _oouts == null ? null
        : fbBuilder.writeList(_oouts!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    fbBuilder.startTable(9);
    fbBuilder.addUint32(0, _height);
    fbBuilder.addUint32(1, _timestamp);
    fbBuilder.addOffset(2, txidOffset);
    fbBuilder.addOffset(3, tinsOffset);
    fbBuilder.addOffset(4, toutsOffset);
    fbBuilder.addOffset(5, sinsOffset);
    fbBuilder.addOffset(6, soutsOffset);
    fbBuilder.addOffset(7, oinsOffset);
    fbBuilder.addOffset(8, ooutsOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class InputTransparent {
  InputTransparent._(this._bc, this._bcOffset);
  factory InputTransparent(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<InputTransparent> reader = _InputTransparentReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<int>? get txid => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 4);
  int get vout => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 6, 0);
  String? get address => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 8);
  int get value => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 10, 0);

  @override
  String toString() {
    return 'InputTransparent{txid: ${txid}, vout: ${vout}, address: ${address}, value: ${value}}';
  }

  InputTransparentT unpack() => InputTransparentT(
      txid: const fb.Uint8ListReader(lazy: false).vTableGetNullable(_bc, _bcOffset, 4),
      vout: vout,
      address: address,
      value: value);

  static int pack(fb.Builder fbBuilder, InputTransparentT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class InputTransparentT implements fb.Packable {
  List<int>? txid;
  int vout;
  String? address;
  int value;

  InputTransparentT({
      this.txid,
      this.vout = 0,
      this.address,
      this.value = 0});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? txidOffset = txid == null ? null
        : fbBuilder.writeListUint8(txid!);
    final int? addressOffset = address == null ? null
        : fbBuilder.writeString(address!);
    fbBuilder.startTable(4);
    fbBuilder.addOffset(0, txidOffset);
    fbBuilder.addUint32(1, vout);
    fbBuilder.addOffset(2, addressOffset);
    fbBuilder.addUint64(3, value);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'InputTransparentT{txid: ${txid}, vout: ${vout}, address: ${address}, value: ${value}}';
  }
}

class _InputTransparentReader extends fb.TableReader<InputTransparent> {
  const _InputTransparentReader();

  @override
  InputTransparent createObject(fb.BufferContext bc, int offset) => 
    InputTransparent._(bc, offset);
}

class InputTransparentBuilder {
  InputTransparentBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(4);
  }

  int addTxidOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addVout(int? vout) {
    fbBuilder.addUint32(1, vout);
    return fbBuilder.offset;
  }
  int addAddressOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addValue(int? value) {
    fbBuilder.addUint64(3, value);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class InputTransparentObjectBuilder extends fb.ObjectBuilder {
  final List<int>? _txid;
  final int? _vout;
  final String? _address;
  final int? _value;

  InputTransparentObjectBuilder({
    List<int>? txid,
    int? vout,
    String? address,
    int? value,
  })
      : _txid = txid,
        _vout = vout,
        _address = address,
        _value = value;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? txidOffset = _txid == null ? null
        : fbBuilder.writeListUint8(_txid!);
    final int? addressOffset = _address == null ? null
        : fbBuilder.writeString(_address!);
    fbBuilder.startTable(4);
    fbBuilder.addOffset(0, txidOffset);
    fbBuilder.addUint32(1, _vout);
    fbBuilder.addOffset(2, addressOffset);
    fbBuilder.addUint64(3, _value);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class OutputTransparent {
  OutputTransparent._(this._bc, this._bcOffset);
  factory OutputTransparent(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<OutputTransparent> reader = _OutputTransparentReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get address => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  int get value => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 6, 0);

  @override
  String toString() {
    return 'OutputTransparent{address: ${address}, value: ${value}}';
  }

  OutputTransparentT unpack() => OutputTransparentT(
      address: address,
      value: value);

  static int pack(fb.Builder fbBuilder, OutputTransparentT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class OutputTransparentT implements fb.Packable {
  String? address;
  int value;

  OutputTransparentT({
      this.address,
      this.value = 0});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? addressOffset = address == null ? null
        : fbBuilder.writeString(address!);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, addressOffset);
    fbBuilder.addUint64(1, value);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'OutputTransparentT{address: ${address}, value: ${value}}';
  }
}

class _OutputTransparentReader extends fb.TableReader<OutputTransparent> {
  const _OutputTransparentReader();

  @override
  OutputTransparent createObject(fb.BufferContext bc, int offset) => 
    OutputTransparent._(bc, offset);
}

class OutputTransparentBuilder {
  OutputTransparentBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addAddressOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addValue(int? value) {
    fbBuilder.addUint64(1, value);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class OutputTransparentObjectBuilder extends fb.ObjectBuilder {
  final String? _address;
  final int? _value;

  OutputTransparentObjectBuilder({
    String? address,
    int? value,
  })
      : _address = address,
        _value = value;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? addressOffset = _address == null ? null
        : fbBuilder.writeString(_address!);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, addressOffset);
    fbBuilder.addUint64(1, _value);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class InputShielded {
  InputShielded._(this._bc, this._bcOffset);
  factory InputShielded(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<InputShielded> reader = _InputShieldedReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<int>? get nf => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 4);
  String? get address => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);
  int get value => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 8, 0);
  List<int>? get rcm => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 10);
  List<int>? get rho => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 12);

  @override
  String toString() {
    return 'InputShielded{nf: ${nf}, address: ${address}, value: ${value}, rcm: ${rcm}, rho: ${rho}}';
  }

  InputShieldedT unpack() => InputShieldedT(
      nf: const fb.Uint8ListReader(lazy: false).vTableGetNullable(_bc, _bcOffset, 4),
      address: address,
      value: value,
      rcm: const fb.Uint8ListReader(lazy: false).vTableGetNullable(_bc, _bcOffset, 10),
      rho: const fb.Uint8ListReader(lazy: false).vTableGetNullable(_bc, _bcOffset, 12));

  static int pack(fb.Builder fbBuilder, InputShieldedT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class InputShieldedT implements fb.Packable {
  List<int>? nf;
  String? address;
  int value;
  List<int>? rcm;
  List<int>? rho;

  InputShieldedT({
      this.nf,
      this.address,
      this.value = 0,
      this.rcm,
      this.rho});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? nfOffset = nf == null ? null
        : fbBuilder.writeListUint8(nf!);
    final int? addressOffset = address == null ? null
        : fbBuilder.writeString(address!);
    final int? rcmOffset = rcm == null ? null
        : fbBuilder.writeListUint8(rcm!);
    final int? rhoOffset = rho == null ? null
        : fbBuilder.writeListUint8(rho!);
    fbBuilder.startTable(5);
    fbBuilder.addOffset(0, nfOffset);
    fbBuilder.addOffset(1, addressOffset);
    fbBuilder.addUint64(2, value);
    fbBuilder.addOffset(3, rcmOffset);
    fbBuilder.addOffset(4, rhoOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'InputShieldedT{nf: ${nf}, address: ${address}, value: ${value}, rcm: ${rcm}, rho: ${rho}}';
  }
}

class _InputShieldedReader extends fb.TableReader<InputShielded> {
  const _InputShieldedReader();

  @override
  InputShielded createObject(fb.BufferContext bc, int offset) => 
    InputShielded._(bc, offset);
}

class InputShieldedBuilder {
  InputShieldedBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(5);
  }

  int addNfOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addAddressOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addValue(int? value) {
    fbBuilder.addUint64(2, value);
    return fbBuilder.offset;
  }
  int addRcmOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }
  int addRhoOffset(int? offset) {
    fbBuilder.addOffset(4, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class InputShieldedObjectBuilder extends fb.ObjectBuilder {
  final List<int>? _nf;
  final String? _address;
  final int? _value;
  final List<int>? _rcm;
  final List<int>? _rho;

  InputShieldedObjectBuilder({
    List<int>? nf,
    String? address,
    int? value,
    List<int>? rcm,
    List<int>? rho,
  })
      : _nf = nf,
        _address = address,
        _value = value,
        _rcm = rcm,
        _rho = rho;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? nfOffset = _nf == null ? null
        : fbBuilder.writeListUint8(_nf!);
    final int? addressOffset = _address == null ? null
        : fbBuilder.writeString(_address!);
    final int? rcmOffset = _rcm == null ? null
        : fbBuilder.writeListUint8(_rcm!);
    final int? rhoOffset = _rho == null ? null
        : fbBuilder.writeListUint8(_rho!);
    fbBuilder.startTable(5);
    fbBuilder.addOffset(0, nfOffset);
    fbBuilder.addOffset(1, addressOffset);
    fbBuilder.addUint64(2, _value);
    fbBuilder.addOffset(3, rcmOffset);
    fbBuilder.addOffset(4, rhoOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class OutputShielded {
  OutputShielded._(this._bc, this._bcOffset);
  factory OutputShielded(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<OutputShielded> reader = _OutputShieldedReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  bool get incoming => const fb.BoolReader().vTableGet(_bc, _bcOffset, 4, false);
  List<int>? get cmx => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 6);
  String? get address => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 8);
  int get value => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 10, 0);
  List<int>? get rcm => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 12);
  List<int>? get rho => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 14);
  String? get memo => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 16);

  @override
  String toString() {
    return 'OutputShielded{incoming: ${incoming}, cmx: ${cmx}, address: ${address}, value: ${value}, rcm: ${rcm}, rho: ${rho}, memo: ${memo}}';
  }

  OutputShieldedT unpack() => OutputShieldedT(
      incoming: incoming,
      cmx: const fb.Uint8ListReader(lazy: false).vTableGetNullable(_bc, _bcOffset, 6),
      address: address,
      value: value,
      rcm: const fb.Uint8ListReader(lazy: false).vTableGetNullable(_bc, _bcOffset, 12),
      rho: const fb.Uint8ListReader(lazy: false).vTableGetNullable(_bc, _bcOffset, 14),
      memo: memo);

  static int pack(fb.Builder fbBuilder, OutputShieldedT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class OutputShieldedT implements fb.Packable {
  bool incoming;
  List<int>? cmx;
  String? address;
  int value;
  List<int>? rcm;
  List<int>? rho;
  String? memo;

  OutputShieldedT({
      this.incoming = false,
      this.cmx,
      this.address,
      this.value = 0,
      this.rcm,
      this.rho,
      this.memo});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? cmxOffset = cmx == null ? null
        : fbBuilder.writeListUint8(cmx!);
    final int? addressOffset = address == null ? null
        : fbBuilder.writeString(address!);
    final int? rcmOffset = rcm == null ? null
        : fbBuilder.writeListUint8(rcm!);
    final int? rhoOffset = rho == null ? null
        : fbBuilder.writeListUint8(rho!);
    final int? memoOffset = memo == null ? null
        : fbBuilder.writeString(memo!);
    fbBuilder.startTable(7);
    fbBuilder.addBool(0, incoming);
    fbBuilder.addOffset(1, cmxOffset);
    fbBuilder.addOffset(2, addressOffset);
    fbBuilder.addUint64(3, value);
    fbBuilder.addOffset(4, rcmOffset);
    fbBuilder.addOffset(5, rhoOffset);
    fbBuilder.addOffset(6, memoOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'OutputShieldedT{incoming: ${incoming}, cmx: ${cmx}, address: ${address}, value: ${value}, rcm: ${rcm}, rho: ${rho}, memo: ${memo}}';
  }
}

class _OutputShieldedReader extends fb.TableReader<OutputShielded> {
  const _OutputShieldedReader();

  @override
  OutputShielded createObject(fb.BufferContext bc, int offset) => 
    OutputShielded._(bc, offset);
}

class OutputShieldedBuilder {
  OutputShieldedBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(7);
  }

  int addIncoming(bool? incoming) {
    fbBuilder.addBool(0, incoming);
    return fbBuilder.offset;
  }
  int addCmxOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addAddressOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addValue(int? value) {
    fbBuilder.addUint64(3, value);
    return fbBuilder.offset;
  }
  int addRcmOffset(int? offset) {
    fbBuilder.addOffset(4, offset);
    return fbBuilder.offset;
  }
  int addRhoOffset(int? offset) {
    fbBuilder.addOffset(5, offset);
    return fbBuilder.offset;
  }
  int addMemoOffset(int? offset) {
    fbBuilder.addOffset(6, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class OutputShieldedObjectBuilder extends fb.ObjectBuilder {
  final bool? _incoming;
  final List<int>? _cmx;
  final String? _address;
  final int? _value;
  final List<int>? _rcm;
  final List<int>? _rho;
  final String? _memo;

  OutputShieldedObjectBuilder({
    bool? incoming,
    List<int>? cmx,
    String? address,
    int? value,
    List<int>? rcm,
    List<int>? rho,
    String? memo,
  })
      : _incoming = incoming,
        _cmx = cmx,
        _address = address,
        _value = value,
        _rcm = rcm,
        _rho = rho,
        _memo = memo;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? cmxOffset = _cmx == null ? null
        : fbBuilder.writeListUint8(_cmx!);
    final int? addressOffset = _address == null ? null
        : fbBuilder.writeString(_address!);
    final int? rcmOffset = _rcm == null ? null
        : fbBuilder.writeListUint8(_rcm!);
    final int? rhoOffset = _rho == null ? null
        : fbBuilder.writeListUint8(_rho!);
    final int? memoOffset = _memo == null ? null
        : fbBuilder.writeString(_memo!);
    fbBuilder.startTable(7);
    fbBuilder.addBool(0, _incoming);
    fbBuilder.addOffset(1, cmxOffset);
    fbBuilder.addOffset(2, addressOffset);
    fbBuilder.addUint64(3, _value);
    fbBuilder.addOffset(4, rcmOffset);
    fbBuilder.addOffset(5, rhoOffset);
    fbBuilder.addOffset(6, memoOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class ShieldedNote {
  ShieldedNote._(this._bc, this._bcOffset);
  factory ShieldedNote(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<ShieldedNote> reader = _ShieldedNoteReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get height => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 4, 0);
  int get confirmations => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 6, 0);
  int get timestamp => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 8, 0);
  int get value => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 10, 0);
  bool get orchard => const fb.BoolReader().vTableGet(_bc, _bcOffset, 12, false);
  bool get excluded => const fb.BoolReader().vTableGet(_bc, _bcOffset, 14, false);

  @override
  String toString() {
    return 'ShieldedNote{height: ${height}, confirmations: ${confirmations}, timestamp: ${timestamp}, value: ${value}, orchard: ${orchard}, excluded: ${excluded}}';
  }

  ShieldedNoteT unpack() => ShieldedNoteT(
      height: height,
      confirmations: confirmations,
      timestamp: timestamp,
      value: value,
      orchard: orchard,
      excluded: excluded);

  static int pack(fb.Builder fbBuilder, ShieldedNoteT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class ShieldedNoteT implements fb.Packable {
  int height;
  int confirmations;
  int timestamp;
  int value;
  bool orchard;
  bool excluded;

  ShieldedNoteT({
      this.height = 0,
      this.confirmations = 0,
      this.timestamp = 0,
      this.value = 0,
      this.orchard = false,
      this.excluded = false});

  @override
  int pack(fb.Builder fbBuilder) {
    fbBuilder.startTable(6);
    fbBuilder.addUint32(0, height);
    fbBuilder.addUint32(1, confirmations);
    fbBuilder.addUint32(2, timestamp);
    fbBuilder.addUint64(3, value);
    fbBuilder.addBool(4, orchard);
    fbBuilder.addBool(5, excluded);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'ShieldedNoteT{height: ${height}, confirmations: ${confirmations}, timestamp: ${timestamp}, value: ${value}, orchard: ${orchard}, excluded: ${excluded}}';
  }
}

class _ShieldedNoteReader extends fb.TableReader<ShieldedNote> {
  const _ShieldedNoteReader();

  @override
  ShieldedNote createObject(fb.BufferContext bc, int offset) => 
    ShieldedNote._(bc, offset);
}

class ShieldedNoteBuilder {
  ShieldedNoteBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(6);
  }

  int addHeight(int? height) {
    fbBuilder.addUint32(0, height);
    return fbBuilder.offset;
  }
  int addConfirmations(int? confirmations) {
    fbBuilder.addUint32(1, confirmations);
    return fbBuilder.offset;
  }
  int addTimestamp(int? timestamp) {
    fbBuilder.addUint32(2, timestamp);
    return fbBuilder.offset;
  }
  int addValue(int? value) {
    fbBuilder.addUint64(3, value);
    return fbBuilder.offset;
  }
  int addOrchard(bool? orchard) {
    fbBuilder.addBool(4, orchard);
    return fbBuilder.offset;
  }
  int addExcluded(bool? excluded) {
    fbBuilder.addBool(5, excluded);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ShieldedNoteObjectBuilder extends fb.ObjectBuilder {
  final int? _height;
  final int? _confirmations;
  final int? _timestamp;
  final int? _value;
  final bool? _orchard;
  final bool? _excluded;

  ShieldedNoteObjectBuilder({
    int? height,
    int? confirmations,
    int? timestamp,
    int? value,
    bool? orchard,
    bool? excluded,
  })
      : _height = height,
        _confirmations = confirmations,
        _timestamp = timestamp,
        _value = value,
        _orchard = orchard,
        _excluded = excluded;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(6);
    fbBuilder.addUint32(0, _height);
    fbBuilder.addUint32(1, _confirmations);
    fbBuilder.addUint32(2, _timestamp);
    fbBuilder.addUint64(3, _value);
    fbBuilder.addBool(4, _orchard);
    fbBuilder.addBool(5, _excluded);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class ShieldedMessage {
  ShieldedMessage._(this._bc, this._bcOffset);
  factory ShieldedMessage(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<ShieldedMessage> reader = _ShieldedMessageReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get idMsg => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 4, 0);
  int get account => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 6, 0);
  int get idTx => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 8, 0);
  List<int>? get txid => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 10);
  int get height => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 12, 0);
  int get timestamp => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 14, 0);
  bool get incoming => const fb.BoolReader().vTableGet(_bc, _bcOffset, 16, false);
  int get nout => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 18, 0);
  String? get sender => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 20);
  String? get recipient => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 22);
  String? get subject => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 24);
  String? get body => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 26);
  bool get read => const fb.BoolReader().vTableGet(_bc, _bcOffset, 28, false);

  @override
  String toString() {
    return 'ShieldedMessage{idMsg: ${idMsg}, account: ${account}, idTx: ${idTx}, txid: ${txid}, height: ${height}, timestamp: ${timestamp}, incoming: ${incoming}, nout: ${nout}, sender: ${sender}, recipient: ${recipient}, subject: ${subject}, body: ${body}, read: ${read}}';
  }

  ShieldedMessageT unpack() => ShieldedMessageT(
      idMsg: idMsg,
      account: account,
      idTx: idTx,
      txid: const fb.Uint8ListReader(lazy: false).vTableGetNullable(_bc, _bcOffset, 10),
      height: height,
      timestamp: timestamp,
      incoming: incoming,
      nout: nout,
      sender: sender,
      recipient: recipient,
      subject: subject,
      body: body,
      read: read);

  static int pack(fb.Builder fbBuilder, ShieldedMessageT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class ShieldedMessageT implements fb.Packable {
  int idMsg;
  int account;
  int idTx;
  List<int>? txid;
  int height;
  int timestamp;
  bool incoming;
  int nout;
  String? sender;
  String? recipient;
  String? subject;
  String? body;
  bool read;

  ShieldedMessageT({
      this.idMsg = 0,
      this.account = 0,
      this.idTx = 0,
      this.txid,
      this.height = 0,
      this.timestamp = 0,
      this.incoming = false,
      this.nout = 0,
      this.sender,
      this.recipient,
      this.subject,
      this.body,
      this.read = false});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? txidOffset = txid == null ? null
        : fbBuilder.writeListUint8(txid!);
    final int? senderOffset = sender == null ? null
        : fbBuilder.writeString(sender!);
    final int? recipientOffset = recipient == null ? null
        : fbBuilder.writeString(recipient!);
    final int? subjectOffset = subject == null ? null
        : fbBuilder.writeString(subject!);
    final int? bodyOffset = body == null ? null
        : fbBuilder.writeString(body!);
    fbBuilder.startTable(13);
    fbBuilder.addUint32(0, idMsg);
    fbBuilder.addUint32(1, account);
    fbBuilder.addUint32(2, idTx);
    fbBuilder.addOffset(3, txidOffset);
    fbBuilder.addUint32(4, height);
    fbBuilder.addUint32(5, timestamp);
    fbBuilder.addBool(6, incoming);
    fbBuilder.addUint32(7, nout);
    fbBuilder.addOffset(8, senderOffset);
    fbBuilder.addOffset(9, recipientOffset);
    fbBuilder.addOffset(10, subjectOffset);
    fbBuilder.addOffset(11, bodyOffset);
    fbBuilder.addBool(12, read);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'ShieldedMessageT{idMsg: ${idMsg}, account: ${account}, idTx: ${idTx}, txid: ${txid}, height: ${height}, timestamp: ${timestamp}, incoming: ${incoming}, nout: ${nout}, sender: ${sender}, recipient: ${recipient}, subject: ${subject}, body: ${body}, read: ${read}}';
  }
}

class _ShieldedMessageReader extends fb.TableReader<ShieldedMessage> {
  const _ShieldedMessageReader();

  @override
  ShieldedMessage createObject(fb.BufferContext bc, int offset) => 
    ShieldedMessage._(bc, offset);
}

class ShieldedMessageBuilder {
  ShieldedMessageBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(13);
  }

  int addIdMsg(int? idMsg) {
    fbBuilder.addUint32(0, idMsg);
    return fbBuilder.offset;
  }
  int addAccount(int? account) {
    fbBuilder.addUint32(1, account);
    return fbBuilder.offset;
  }
  int addIdTx(int? idTx) {
    fbBuilder.addUint32(2, idTx);
    return fbBuilder.offset;
  }
  int addTxidOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }
  int addHeight(int? height) {
    fbBuilder.addUint32(4, height);
    return fbBuilder.offset;
  }
  int addTimestamp(int? timestamp) {
    fbBuilder.addUint32(5, timestamp);
    return fbBuilder.offset;
  }
  int addIncoming(bool? incoming) {
    fbBuilder.addBool(6, incoming);
    return fbBuilder.offset;
  }
  int addNout(int? nout) {
    fbBuilder.addUint32(7, nout);
    return fbBuilder.offset;
  }
  int addSenderOffset(int? offset) {
    fbBuilder.addOffset(8, offset);
    return fbBuilder.offset;
  }
  int addRecipientOffset(int? offset) {
    fbBuilder.addOffset(9, offset);
    return fbBuilder.offset;
  }
  int addSubjectOffset(int? offset) {
    fbBuilder.addOffset(10, offset);
    return fbBuilder.offset;
  }
  int addBodyOffset(int? offset) {
    fbBuilder.addOffset(11, offset);
    return fbBuilder.offset;
  }
  int addRead(bool? read) {
    fbBuilder.addBool(12, read);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ShieldedMessageObjectBuilder extends fb.ObjectBuilder {
  final int? _idMsg;
  final int? _account;
  final int? _idTx;
  final List<int>? _txid;
  final int? _height;
  final int? _timestamp;
  final bool? _incoming;
  final int? _nout;
  final String? _sender;
  final String? _recipient;
  final String? _subject;
  final String? _body;
  final bool? _read;

  ShieldedMessageObjectBuilder({
    int? idMsg,
    int? account,
    int? idTx,
    List<int>? txid,
    int? height,
    int? timestamp,
    bool? incoming,
    int? nout,
    String? sender,
    String? recipient,
    String? subject,
    String? body,
    bool? read,
  })
      : _idMsg = idMsg,
        _account = account,
        _idTx = idTx,
        _txid = txid,
        _height = height,
        _timestamp = timestamp,
        _incoming = incoming,
        _nout = nout,
        _sender = sender,
        _recipient = recipient,
        _subject = subject,
        _body = body,
        _read = read;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? txidOffset = _txid == null ? null
        : fbBuilder.writeListUint8(_txid!);
    final int? senderOffset = _sender == null ? null
        : fbBuilder.writeString(_sender!);
    final int? recipientOffset = _recipient == null ? null
        : fbBuilder.writeString(_recipient!);
    final int? subjectOffset = _subject == null ? null
        : fbBuilder.writeString(_subject!);
    final int? bodyOffset = _body == null ? null
        : fbBuilder.writeString(_body!);
    fbBuilder.startTable(13);
    fbBuilder.addUint32(0, _idMsg);
    fbBuilder.addUint32(1, _account);
    fbBuilder.addUint32(2, _idTx);
    fbBuilder.addOffset(3, txidOffset);
    fbBuilder.addUint32(4, _height);
    fbBuilder.addUint32(5, _timestamp);
    fbBuilder.addBool(6, _incoming);
    fbBuilder.addUint32(7, _nout);
    fbBuilder.addOffset(8, senderOffset);
    fbBuilder.addOffset(9, recipientOffset);
    fbBuilder.addOffset(10, subjectOffset);
    fbBuilder.addOffset(11, bodyOffset);
    fbBuilder.addBool(12, _read);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Uareceivers {
  Uareceivers._(this._bc, this._bcOffset);
  factory Uareceivers(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Uareceivers> reader = _UareceiversReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get transparent => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  String? get sapling => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);
  String? get orchard => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 8);

  @override
  String toString() {
    return 'Uareceivers{transparent: ${transparent}, sapling: ${sapling}, orchard: ${orchard}}';
  }

  UareceiversT unpack() => UareceiversT(
      transparent: transparent,
      sapling: sapling,
      orchard: orchard);

  static int pack(fb.Builder fbBuilder, UareceiversT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class UareceiversT implements fb.Packable {
  String? transparent;
  String? sapling;
  String? orchard;

  UareceiversT({
      this.transparent,
      this.sapling,
      this.orchard});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? transparentOffset = transparent == null ? null
        : fbBuilder.writeString(transparent!);
    final int? saplingOffset = sapling == null ? null
        : fbBuilder.writeString(sapling!);
    final int? orchardOffset = orchard == null ? null
        : fbBuilder.writeString(orchard!);
    fbBuilder.startTable(3);
    fbBuilder.addOffset(0, transparentOffset);
    fbBuilder.addOffset(1, saplingOffset);
    fbBuilder.addOffset(2, orchardOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'UareceiversT{transparent: ${transparent}, sapling: ${sapling}, orchard: ${orchard}}';
  }
}

class _UareceiversReader extends fb.TableReader<Uareceivers> {
  const _UareceiversReader();

  @override
  Uareceivers createObject(fb.BufferContext bc, int offset) => 
    Uareceivers._(bc, offset);
}

class UareceiversBuilder {
  UareceiversBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addTransparentOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addSaplingOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addOrchardOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class UareceiversObjectBuilder extends fb.ObjectBuilder {
  final String? _transparent;
  final String? _sapling;
  final String? _orchard;

  UareceiversObjectBuilder({
    String? transparent,
    String? sapling,
    String? orchard,
  })
      : _transparent = transparent,
        _sapling = sapling,
        _orchard = orchard;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? transparentOffset = _transparent == null ? null
        : fbBuilder.writeString(_transparent!);
    final int? saplingOffset = _sapling == null ? null
        : fbBuilder.writeString(_sapling!);
    final int? orchardOffset = _orchard == null ? null
        : fbBuilder.writeString(_orchard!);
    fbBuilder.startTable(3);
    fbBuilder.addOffset(0, transparentOffset);
    fbBuilder.addOffset(1, saplingOffset);
    fbBuilder.addOffset(2, orchardOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class PaymentRequest {
  PaymentRequest._(this._bc, this._bcOffset);
  factory PaymentRequest(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<PaymentRequest> reader = _PaymentRequestReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get address => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  int get amount => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 6, 0);
  String? get memoString => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 8);
  List<int>? get memoBytes => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 10);

  @override
  String toString() {
    return 'PaymentRequest{address: ${address}, amount: ${amount}, memoString: ${memoString}, memoBytes: ${memoBytes}}';
  }

  PaymentRequestT unpack() => PaymentRequestT(
      address: address,
      amount: amount,
      memoString: memoString,
      memoBytes: const fb.Uint8ListReader(lazy: false).vTableGetNullable(_bc, _bcOffset, 10));

  static int pack(fb.Builder fbBuilder, PaymentRequestT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class PaymentRequestT implements fb.Packable {
  String? address;
  int amount;
  String? memoString;
  List<int>? memoBytes;

  PaymentRequestT({
      this.address,
      this.amount = 0,
      this.memoString,
      this.memoBytes});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? addressOffset = address == null ? null
        : fbBuilder.writeString(address!);
    final int? memoStringOffset = memoString == null ? null
        : fbBuilder.writeString(memoString!);
    final int? memoBytesOffset = memoBytes == null ? null
        : fbBuilder.writeListUint8(memoBytes!);
    fbBuilder.startTable(4);
    fbBuilder.addOffset(0, addressOffset);
    fbBuilder.addUint64(1, amount);
    fbBuilder.addOffset(2, memoStringOffset);
    fbBuilder.addOffset(3, memoBytesOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'PaymentRequestT{address: ${address}, amount: ${amount}, memoString: ${memoString}, memoBytes: ${memoBytes}}';
  }
}

class _PaymentRequestReader extends fb.TableReader<PaymentRequest> {
  const _PaymentRequestReader();

  @override
  PaymentRequest createObject(fb.BufferContext bc, int offset) => 
    PaymentRequest._(bc, offset);
}

class PaymentRequestBuilder {
  PaymentRequestBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(4);
  }

  int addAddressOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addAmount(int? amount) {
    fbBuilder.addUint64(1, amount);
    return fbBuilder.offset;
  }
  int addMemoStringOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addMemoBytesOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class PaymentRequestObjectBuilder extends fb.ObjectBuilder {
  final String? _address;
  final int? _amount;
  final String? _memoString;
  final List<int>? _memoBytes;

  PaymentRequestObjectBuilder({
    String? address,
    int? amount,
    String? memoString,
    List<int>? memoBytes,
  })
      : _address = address,
        _amount = amount,
        _memoString = memoString,
        _memoBytes = memoBytes;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? addressOffset = _address == null ? null
        : fbBuilder.writeString(_address!);
    final int? memoStringOffset = _memoString == null ? null
        : fbBuilder.writeString(_memoString!);
    final int? memoBytesOffset = _memoBytes == null ? null
        : fbBuilder.writeListUint8(_memoBytes!);
    fbBuilder.startTable(4);
    fbBuilder.addOffset(0, addressOffset);
    fbBuilder.addUint64(1, _amount);
    fbBuilder.addOffset(2, memoStringOffset);
    fbBuilder.addOffset(3, memoBytesOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class PaymentRequests {
  PaymentRequests._(this._bc, this._bcOffset);
  factory PaymentRequests(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<PaymentRequests> reader = _PaymentRequestsReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<PaymentRequest>? get payments => const fb.ListReader<PaymentRequest>(PaymentRequest.reader).vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'PaymentRequests{payments: ${payments}}';
  }

  PaymentRequestsT unpack() => PaymentRequestsT(
      payments: payments?.map((e) => e.unpack()).toList());

  static int pack(fb.Builder fbBuilder, PaymentRequestsT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class PaymentRequestsT implements fb.Packable {
  List<PaymentRequestT>? payments;

  PaymentRequestsT({
      this.payments});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? paymentsOffset = payments == null ? null
        : fbBuilder.writeList(payments!.map((b) => b.pack(fbBuilder)).toList());
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, paymentsOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'PaymentRequestsT{payments: ${payments}}';
  }
}

class _PaymentRequestsReader extends fb.TableReader<PaymentRequests> {
  const _PaymentRequestsReader();

  @override
  PaymentRequests createObject(fb.BufferContext bc, int offset) => 
    PaymentRequests._(bc, offset);
}

class PaymentRequestsBuilder {
  PaymentRequestsBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addPaymentsOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class PaymentRequestsObjectBuilder extends fb.ObjectBuilder {
  final List<PaymentRequestObjectBuilder>? _payments;

  PaymentRequestsObjectBuilder({
    List<PaymentRequestObjectBuilder>? payments,
  })
      : _payments = payments;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? paymentsOffset = _payments == null ? null
        : fbBuilder.writeList(_payments!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, paymentsOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class AccountName {
  AccountName._(this._bc, this._bcOffset);
  factory AccountName(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<AccountName> reader = _AccountNameReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get id => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 4, 0);
  String? get name => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);
  String? get saplingAddress => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 8);
  int get birth => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 10, 0);

  @override
  String toString() {
    return 'AccountName{id: ${id}, name: ${name}, saplingAddress: ${saplingAddress}, birth: ${birth}}';
  }

  AccountNameT unpack() => AccountNameT(
      id: id,
      name: name,
      saplingAddress: saplingAddress,
      birth: birth);

  static int pack(fb.Builder fbBuilder, AccountNameT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class AccountNameT implements fb.Packable {
  int id;
  String? name;
  String? saplingAddress;
  int birth;

  AccountNameT({
      this.id = 0,
      this.name,
      this.saplingAddress,
      this.birth = 0});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? nameOffset = name == null ? null
        : fbBuilder.writeString(name!);
    final int? saplingAddressOffset = saplingAddress == null ? null
        : fbBuilder.writeString(saplingAddress!);
    fbBuilder.startTable(4);
    fbBuilder.addUint32(0, id);
    fbBuilder.addOffset(1, nameOffset);
    fbBuilder.addOffset(2, saplingAddressOffset);
    fbBuilder.addUint32(3, birth);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'AccountNameT{id: ${id}, name: ${name}, saplingAddress: ${saplingAddress}, birth: ${birth}}';
  }
}

class _AccountNameReader extends fb.TableReader<AccountName> {
  const _AccountNameReader();

  @override
  AccountName createObject(fb.BufferContext bc, int offset) => 
    AccountName._(bc, offset);
}

class AccountNameBuilder {
  AccountNameBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(4);
  }

  int addId(int? id) {
    fbBuilder.addUint32(0, id);
    return fbBuilder.offset;
  }
  int addNameOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addSaplingAddressOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addBirth(int? birth) {
    fbBuilder.addUint32(3, birth);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class AccountNameObjectBuilder extends fb.ObjectBuilder {
  final int? _id;
  final String? _name;
  final String? _saplingAddress;
  final int? _birth;

  AccountNameObjectBuilder({
    int? id,
    String? name,
    String? saplingAddress,
    int? birth,
  })
      : _id = id,
        _name = name,
        _saplingAddress = saplingAddress,
        _birth = birth;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? nameOffset = _name == null ? null
        : fbBuilder.writeString(_name!);
    final int? saplingAddressOffset = _saplingAddress == null ? null
        : fbBuilder.writeString(_saplingAddress!);
    fbBuilder.startTable(4);
    fbBuilder.addUint32(0, _id);
    fbBuilder.addOffset(1, nameOffset);
    fbBuilder.addOffset(2, saplingAddressOffset);
    fbBuilder.addUint32(3, _birth);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class ContactCard {
  ContactCard._(this._bc, this._bcOffset);
  factory ContactCard(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<ContactCard> reader = _ContactCardReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get id => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 4, 0);
  int get account => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 6, 0);
  String? get name => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 8);
  String? get address => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 10);
  bool get saved => const fb.BoolReader().vTableGet(_bc, _bcOffset, 12, false);

  @override
  String toString() {
    return 'ContactCard{id: ${id}, account: ${account}, name: ${name}, address: ${address}, saved: ${saved}}';
  }

  ContactCardT unpack() => ContactCardT(
      id: id,
      account: account,
      name: name,
      address: address,
      saved: saved);

  static int pack(fb.Builder fbBuilder, ContactCardT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class ContactCardT implements fb.Packable {
  int id;
  int account;
  String? name;
  String? address;
  bool saved;

  ContactCardT({
      this.id = 0,
      this.account = 0,
      this.name,
      this.address,
      this.saved = false});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? nameOffset = name == null ? null
        : fbBuilder.writeString(name!);
    final int? addressOffset = address == null ? null
        : fbBuilder.writeString(address!);
    fbBuilder.startTable(5);
    fbBuilder.addUint32(0, id);
    fbBuilder.addUint32(1, account);
    fbBuilder.addOffset(2, nameOffset);
    fbBuilder.addOffset(3, addressOffset);
    fbBuilder.addBool(4, saved);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'ContactCardT{id: ${id}, account: ${account}, name: ${name}, address: ${address}, saved: ${saved}}';
  }
}

class _ContactCardReader extends fb.TableReader<ContactCard> {
  const _ContactCardReader();

  @override
  ContactCard createObject(fb.BufferContext bc, int offset) => 
    ContactCard._(bc, offset);
}

class ContactCardBuilder {
  ContactCardBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(5);
  }

  int addId(int? id) {
    fbBuilder.addUint32(0, id);
    return fbBuilder.offset;
  }
  int addAccount(int? account) {
    fbBuilder.addUint32(1, account);
    return fbBuilder.offset;
  }
  int addNameOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }
  int addAddressOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }
  int addSaved(bool? saved) {
    fbBuilder.addBool(4, saved);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ContactCardObjectBuilder extends fb.ObjectBuilder {
  final int? _id;
  final int? _account;
  final String? _name;
  final String? _address;
  final bool? _saved;

  ContactCardObjectBuilder({
    int? id,
    int? account,
    String? name,
    String? address,
    bool? saved,
  })
      : _id = id,
        _account = account,
        _name = name,
        _address = address,
        _saved = saved;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? nameOffset = _name == null ? null
        : fbBuilder.writeString(_name!);
    final int? addressOffset = _address == null ? null
        : fbBuilder.writeString(_address!);
    fbBuilder.startTable(5);
    fbBuilder.addUint32(0, _id);
    fbBuilder.addUint32(1, _account);
    fbBuilder.addOffset(2, nameOffset);
    fbBuilder.addOffset(3, addressOffset);
    fbBuilder.addBool(4, _saved);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class TransactionRecipient {
  TransactionRecipient._(this._bc, this._bcOffset);
  factory TransactionRecipient(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<TransactionRecipient> reader = _TransactionRecipientReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get address => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  int get amount => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 6, 0);

  @override
  String toString() {
    return 'TransactionRecipient{address: ${address}, amount: ${amount}}';
  }

  TransactionRecipientT unpack() => TransactionRecipientT(
      address: address,
      amount: amount);

  static int pack(fb.Builder fbBuilder, TransactionRecipientT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class TransactionRecipientT implements fb.Packable {
  String? address;
  int amount;

  TransactionRecipientT({
      this.address,
      this.amount = 0});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? addressOffset = address == null ? null
        : fbBuilder.writeString(address!);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, addressOffset);
    fbBuilder.addUint64(1, amount);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'TransactionRecipientT{address: ${address}, amount: ${amount}}';
  }
}

class _TransactionRecipientReader extends fb.TableReader<TransactionRecipient> {
  const _TransactionRecipientReader();

  @override
  TransactionRecipient createObject(fb.BufferContext bc, int offset) => 
    TransactionRecipient._(bc, offset);
}

class TransactionRecipientBuilder {
  TransactionRecipientBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addAddressOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addAmount(int? amount) {
    fbBuilder.addUint64(1, amount);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class TransactionRecipientObjectBuilder extends fb.ObjectBuilder {
  final String? _address;
  final int? _amount;

  TransactionRecipientObjectBuilder({
    String? address,
    int? amount,
  })
      : _address = address,
        _amount = amount;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? addressOffset = _address == null ? null
        : fbBuilder.writeString(_address!);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, addressOffset);
    fbBuilder.addUint64(1, _amount);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class TransactionSummary {
  TransactionSummary._(this._bc, this._bcOffset);
  factory TransactionSummary(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<TransactionSummary> reader = _TransactionSummaryReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get height => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 4, 0);
  List<TransactionRecipient>? get recipients => const fb.ListReader<TransactionRecipient>(TransactionRecipient.reader).vTableGetNullable(_bc, _bcOffset, 6);
  int get transparentIns => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 8, 0);
  int get saplingNet => const fb.Int64Reader().vTableGet(_bc, _bcOffset, 10, 0);
  int get orchardNet => const fb.Int64Reader().vTableGet(_bc, _bcOffset, 12, 0);
  int get fee => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 14, 0);
  List<int>? get data => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 16);
  List<int>? get keys => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 18);

  @override
  String toString() {
    return 'TransactionSummary{height: ${height}, recipients: ${recipients}, transparentIns: ${transparentIns}, saplingNet: ${saplingNet}, orchardNet: ${orchardNet}, fee: ${fee}, data: ${data}, keys: ${keys}}';
  }

  TransactionSummaryT unpack() => TransactionSummaryT(
      height: height,
      recipients: recipients?.map((e) => e.unpack()).toList(),
      transparentIns: transparentIns,
      saplingNet: saplingNet,
      orchardNet: orchardNet,
      fee: fee,
      data: const fb.Uint8ListReader(lazy: false).vTableGetNullable(_bc, _bcOffset, 16),
      keys: const fb.Uint8ListReader(lazy: false).vTableGetNullable(_bc, _bcOffset, 18));

  static int pack(fb.Builder fbBuilder, TransactionSummaryT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class TransactionSummaryT implements fb.Packable {
  int height;
  List<TransactionRecipientT>? recipients;
  int transparentIns;
  int saplingNet;
  int orchardNet;
  int fee;
  List<int>? data;
  List<int>? keys;

  TransactionSummaryT({
      this.height = 0,
      this.recipients,
      this.transparentIns = 0,
      this.saplingNet = 0,
      this.orchardNet = 0,
      this.fee = 0,
      this.data,
      this.keys});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? recipientsOffset = recipients == null ? null
        : fbBuilder.writeList(recipients!.map((b) => b.pack(fbBuilder)).toList());
    final int? dataOffset = data == null ? null
        : fbBuilder.writeListUint8(data!);
    final int? keysOffset = keys == null ? null
        : fbBuilder.writeListUint8(keys!);
    fbBuilder.startTable(8);
    fbBuilder.addUint32(0, height);
    fbBuilder.addOffset(1, recipientsOffset);
    fbBuilder.addUint64(2, transparentIns);
    fbBuilder.addInt64(3, saplingNet);
    fbBuilder.addInt64(4, orchardNet);
    fbBuilder.addUint64(5, fee);
    fbBuilder.addOffset(6, dataOffset);
    fbBuilder.addOffset(7, keysOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'TransactionSummaryT{height: ${height}, recipients: ${recipients}, transparentIns: ${transparentIns}, saplingNet: ${saplingNet}, orchardNet: ${orchardNet}, fee: ${fee}, data: ${data}, keys: ${keys}}';
  }
}

class _TransactionSummaryReader extends fb.TableReader<TransactionSummary> {
  const _TransactionSummaryReader();

  @override
  TransactionSummary createObject(fb.BufferContext bc, int offset) => 
    TransactionSummary._(bc, offset);
}

class TransactionSummaryBuilder {
  TransactionSummaryBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(8);
  }

  int addHeight(int? height) {
    fbBuilder.addUint32(0, height);
    return fbBuilder.offset;
  }
  int addRecipientsOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addTransparentIns(int? transparentIns) {
    fbBuilder.addUint64(2, transparentIns);
    return fbBuilder.offset;
  }
  int addSaplingNet(int? saplingNet) {
    fbBuilder.addInt64(3, saplingNet);
    return fbBuilder.offset;
  }
  int addOrchardNet(int? orchardNet) {
    fbBuilder.addInt64(4, orchardNet);
    return fbBuilder.offset;
  }
  int addFee(int? fee) {
    fbBuilder.addUint64(5, fee);
    return fbBuilder.offset;
  }
  int addDataOffset(int? offset) {
    fbBuilder.addOffset(6, offset);
    return fbBuilder.offset;
  }
  int addKeysOffset(int? offset) {
    fbBuilder.addOffset(7, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class TransactionSummaryObjectBuilder extends fb.ObjectBuilder {
  final int? _height;
  final List<TransactionRecipientObjectBuilder>? _recipients;
  final int? _transparentIns;
  final int? _saplingNet;
  final int? _orchardNet;
  final int? _fee;
  final List<int>? _data;
  final List<int>? _keys;

  TransactionSummaryObjectBuilder({
    int? height,
    List<TransactionRecipientObjectBuilder>? recipients,
    int? transparentIns,
    int? saplingNet,
    int? orchardNet,
    int? fee,
    List<int>? data,
    List<int>? keys,
  })
      : _height = height,
        _recipients = recipients,
        _transparentIns = transparentIns,
        _saplingNet = saplingNet,
        _orchardNet = orchardNet,
        _fee = fee,
        _data = data,
        _keys = keys;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? recipientsOffset = _recipients == null ? null
        : fbBuilder.writeList(_recipients!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    final int? dataOffset = _data == null ? null
        : fbBuilder.writeListUint8(_data!);
    final int? keysOffset = _keys == null ? null
        : fbBuilder.writeListUint8(_keys!);
    fbBuilder.startTable(8);
    fbBuilder.addUint32(0, _height);
    fbBuilder.addOffset(1, recipientsOffset);
    fbBuilder.addUint64(2, _transparentIns);
    fbBuilder.addInt64(3, _saplingNet);
    fbBuilder.addInt64(4, _orchardNet);
    fbBuilder.addUint64(5, _fee);
    fbBuilder.addOffset(6, dataOffset);
    fbBuilder.addOffset(7, keysOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Agekeys {
  Agekeys._(this._bc, this._bcOffset);
  factory Agekeys(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Agekeys> reader = _AgekeysReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get publicKey => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);
  String? get secretKey => const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'Agekeys{publicKey: ${publicKey}, secretKey: ${secretKey}}';
  }

  AgekeysT unpack() => AgekeysT(
      publicKey: publicKey,
      secretKey: secretKey);

  static int pack(fb.Builder fbBuilder, AgekeysT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class AgekeysT implements fb.Packable {
  String? publicKey;
  String? secretKey;

  AgekeysT({
      this.publicKey,
      this.secretKey});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? publicKeyOffset = publicKey == null ? null
        : fbBuilder.writeString(publicKey!);
    final int? secretKeyOffset = secretKey == null ? null
        : fbBuilder.writeString(secretKey!);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, publicKeyOffset);
    fbBuilder.addOffset(1, secretKeyOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'AgekeysT{publicKey: ${publicKey}, secretKey: ${secretKey}}';
  }
}

class _AgekeysReader extends fb.TableReader<Agekeys> {
  const _AgekeysReader();

  @override
  Agekeys createObject(fb.BufferContext bc, int offset) => 
    Agekeys._(bc, offset);
}

class AgekeysBuilder {
  AgekeysBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addPublicKeyOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addSecretKeyOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class AgekeysObjectBuilder extends fb.ObjectBuilder {
  final String? _publicKey;
  final String? _secretKey;

  AgekeysObjectBuilder({
    String? publicKey,
    String? secretKey,
  })
      : _publicKey = publicKey,
        _secretKey = secretKey;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? publicKeyOffset = _publicKey == null ? null
        : fbBuilder.writeString(_publicKey!);
    final int? secretKeyOffset = _secretKey == null ? null
        : fbBuilder.writeString(_secretKey!);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, publicKeyOffset);
    fbBuilder.addOffset(1, secretKeyOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Balance {
  Balance._(this._bc, this._bcOffset);
  factory Balance(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Balance> reader = _BalanceReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get transparent => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 4, 0);
  int get sapling => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 6, 0);
  int get orchard => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 8, 0);

  @override
  String toString() {
    return 'Balance{transparent: ${transparent}, sapling: ${sapling}, orchard: ${orchard}}';
  }

  BalanceT unpack() => BalanceT(
      transparent: transparent,
      sapling: sapling,
      orchard: orchard);

  static int pack(fb.Builder fbBuilder, BalanceT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class BalanceT implements fb.Packable {
  int transparent;
  int sapling;
  int orchard;

  BalanceT({
      this.transparent = 0,
      this.sapling = 0,
      this.orchard = 0});

  @override
  int pack(fb.Builder fbBuilder) {
    fbBuilder.startTable(3);
    fbBuilder.addUint64(0, transparent);
    fbBuilder.addUint64(1, sapling);
    fbBuilder.addUint64(2, orchard);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'BalanceT{transparent: ${transparent}, sapling: ${sapling}, orchard: ${orchard}}';
  }
}

class _BalanceReader extends fb.TableReader<Balance> {
  const _BalanceReader();

  @override
  Balance createObject(fb.BufferContext bc, int offset) => 
    Balance._(bc, offset);
}

class BalanceBuilder {
  BalanceBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addTransparent(int? transparent) {
    fbBuilder.addUint64(0, transparent);
    return fbBuilder.offset;
  }
  int addSapling(int? sapling) {
    fbBuilder.addUint64(1, sapling);
    return fbBuilder.offset;
  }
  int addOrchard(int? orchard) {
    fbBuilder.addUint64(2, orchard);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class BalanceObjectBuilder extends fb.ObjectBuilder {
  final int? _transparent;
  final int? _sapling;
  final int? _orchard;

  BalanceObjectBuilder({
    int? transparent,
    int? sapling,
    int? orchard,
  })
      : _transparent = transparent,
        _sapling = sapling,
        _orchard = orchard;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(3);
    fbBuilder.addUint64(0, _transparent);
    fbBuilder.addUint64(1, _sapling);
    fbBuilder.addUint64(2, _orchard);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Packet {
  Packet._(this._bc, this._bcOffset);
  factory Packet(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Packet> reader = _PacketReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<int>? get data => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'Packet{data: ${data}}';
  }

  PacketT unpack() => PacketT(
      data: const fb.Uint8ListReader(lazy: false).vTableGetNullable(_bc, _bcOffset, 4));

  static int pack(fb.Builder fbBuilder, PacketT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class PacketT implements fb.Packable {
  List<int>? data;

  PacketT({
      this.data});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? dataOffset = data == null ? null
        : fbBuilder.writeListUint8(data!);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, dataOffset);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'PacketT{data: ${data}}';
  }
}

class _PacketReader extends fb.TableReader<Packet> {
  const _PacketReader();

  @override
  Packet createObject(fb.BufferContext bc, int offset) => 
    Packet._(bc, offset);
}

class PacketBuilder {
  PacketBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addDataOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class PacketObjectBuilder extends fb.ObjectBuilder {
  final List<int>? _data;

  PacketObjectBuilder({
    List<int>? data,
  })
      : _data = data;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? dataOffset = _data == null ? null
        : fbBuilder.writeListUint8(_data!);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, dataOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Packets {
  Packets._(this._bc, this._bcOffset);
  factory Packets(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Packets> reader = _PacketsReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<Packet>? get packets => const fb.ListReader<Packet>(Packet.reader).vTableGetNullable(_bc, _bcOffset, 4);
  int get len => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 6, 0);

  @override
  String toString() {
    return 'Packets{packets: ${packets}, len: ${len}}';
  }

  PacketsT unpack() => PacketsT(
      packets: packets?.map((e) => e.unpack()).toList(),
      len: len);

  static int pack(fb.Builder fbBuilder, PacketsT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class PacketsT implements fb.Packable {
  List<PacketT>? packets;
  int len;

  PacketsT({
      this.packets,
      this.len = 0});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? packetsOffset = packets == null ? null
        : fbBuilder.writeList(packets!.map((b) => b.pack(fbBuilder)).toList());
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, packetsOffset);
    fbBuilder.addUint32(1, len);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'PacketsT{packets: ${packets}, len: ${len}}';
  }
}

class _PacketsReader extends fb.TableReader<Packets> {
  const _PacketsReader();

  @override
  Packets createObject(fb.BufferContext bc, int offset) => 
    Packets._(bc, offset);
}

class PacketsBuilder {
  PacketsBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addPacketsOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }
  int addLen(int? len) {
    fbBuilder.addUint32(1, len);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class PacketsObjectBuilder extends fb.ObjectBuilder {
  final List<PacketObjectBuilder>? _packets;
  final int? _len;

  PacketsObjectBuilder({
    List<PacketObjectBuilder>? packets,
    int? len,
  })
      : _packets = packets,
        _len = len;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? packetsOffset = _packets == null ? null
        : fbBuilder.writeList(_packets!.map((b) => b.getOrCreateOffset(fbBuilder)).toList());
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, packetsOffset);
    fbBuilder.addUint32(1, _len);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
class Checkpoint {
  Checkpoint._(this._bc, this._bcOffset);
  factory Checkpoint(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Checkpoint> reader = _CheckpointReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get height => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 4, 0);
  List<int>? get hash => const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 6);
  int get timestamp => const fb.Uint32Reader().vTableGet(_bc, _bcOffset, 8, 0);

  @override
  String toString() {
    return 'Checkpoint{height: ${height}, hash: ${hash}, timestamp: ${timestamp}}';
  }

  CheckpointT unpack() => CheckpointT(
      height: height,
      hash: const fb.Uint8ListReader(lazy: false).vTableGetNullable(_bc, _bcOffset, 6),
      timestamp: timestamp);

  static int pack(fb.Builder fbBuilder, CheckpointT? object) {
    if (object == null) return 0;
    return object.pack(fbBuilder);
  }
}

class CheckpointT implements fb.Packable {
  int height;
  List<int>? hash;
  int timestamp;

  CheckpointT({
      this.height = 0,
      this.hash,
      this.timestamp = 0});

  @override
  int pack(fb.Builder fbBuilder) {
    final int? hashOffset = hash == null ? null
        : fbBuilder.writeListUint8(hash!);
    fbBuilder.startTable(3);
    fbBuilder.addUint32(0, height);
    fbBuilder.addOffset(1, hashOffset);
    fbBuilder.addUint32(2, timestamp);
    return fbBuilder.endTable();
  }

  @override
  String toString() {
    return 'CheckpointT{height: ${height}, hash: ${hash}, timestamp: ${timestamp}}';
  }
}

class _CheckpointReader extends fb.TableReader<Checkpoint> {
  const _CheckpointReader();

  @override
  Checkpoint createObject(fb.BufferContext bc, int offset) => 
    Checkpoint._(bc, offset);
}

class CheckpointBuilder {
  CheckpointBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addHeight(int? height) {
    fbBuilder.addUint32(0, height);
    return fbBuilder.offset;
  }
  int addHashOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }
  int addTimestamp(int? timestamp) {
    fbBuilder.addUint32(2, timestamp);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class CheckpointObjectBuilder extends fb.ObjectBuilder {
  final int? _height;
  final List<int>? _hash;
  final int? _timestamp;

  CheckpointObjectBuilder({
    int? height,
    List<int>? hash,
    int? timestamp,
  })
      : _height = height,
        _hash = hash,
        _timestamp = timestamp;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? hashOffset = _hash == null ? null
        : fbBuilder.writeListUint8(_hash!);
    fbBuilder.startTable(3);
    fbBuilder.addUint32(0, _height);
    fbBuilder.addOffset(1, hashOffset);
    fbBuilder.addUint32(2, _timestamp);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
